/*
  This file will be overwritten by wxDev-C++ at every compile.
  Do not edit this file as your changes will be lost.
  You can, however, include this file and use the defines.
*/
#ifndef PROJECT1_PRIVATE_H
#define PROJECT1_PRIVATE_H

/* VERSION DEFINITIONS */
#define VER_STRING	"0.1.1.1"
#define VER_MAJOR	0
#define VER_MINOR	1
#define VER_RELEASE	1
#define VER_BUILD	1
#define COMPANY_NAME	""
#define FILE_VERSION	"2.0"
#define FILE_DESCRIPTION	""
#define INTERNAL_NAME	""
#define LEGAL_COPYRIGHT	"Renato dos Santos Estecio"
#define LEGAL_TRADEMARKS	""
#define ORIGINAL_FILENAME	""
#define PRODUCT_NAME	"O Passeio do Cavalo"
#define PRODUCT_VERSION	"2.0"

#endif /*PROJECT1_PRIVATE_H*/
